<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerM81Rm44\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerM81Rm44/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerM81Rm44.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerM81Rm44\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerM81Rm44\appAppKernelProdContainer([
    'container.build_hash' => 'M81Rm44',
    'container.build_id' => 'ebd03fae',
    'container.build_time' => 1749842927,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerM81Rm44');
